version: "3.8"

services:
  web:
    build: ./web
    ports:
      - "5001:5000"
    depends_on:
      - mongo
    volumes:
      - ./web:/app
    command: python -m flask run --host=0.0.0.0
    env_file:
      - .env
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: